import sqlite3
from decimal import Decimal


sqlite3.register_adapter(Decimal, lambda d: int(d.quantize(Decimal("0.01")) * Decimal("100")))
sqlite3.register_converter("REAL", lambda b: Decimal(b.decode()).quantize(Decimal("0.01")))

conn = sqlite3.connect("RegisterDatabase", detect_types=sqlite3.PARSE_DECLTYPES)

cursor = conn.cursor()

cursor.execute('''DROP TABLE old_inventory''')
cursor.execute('''DROP TABLE old_sales''')
cursor.execute('''DROP TABLE old_saleitems''')
cursor.execute('''ALTER TABLE Inventory RENAME TO old_inventory''')
cursor.execute('''ALTER TABLE sales RENAME TO old_sales''')
cursor.execute('''ALTER TABLE saleitems RENAME TO old_saleitems''')
cursor.execute('''CREATE TABLE inventory(item_id INTEGER PRIMARY KEY AUTOINCREMENT, item_name TEXT NOT NULL, item_price TWODECINT NOT NULL, item_taxable BOOLEAN, item_barcode TEXT, item_quantity FOURDECINT, category_id INTEGER, subcategory_id INTEGER, vendor_id INTEGER, FOREIGN KEY (category_id) REFERENCES categories(category_id), FOREIGN KEY (subcategory_id) REFERENCES categories(category_id), FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id))''')
cursor.execute('''CREATE TABLE sales(sale_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "non_tax" TWODECINT NOT NULL, "pre_tax" TWODECINT NOT NULL, tax TWODECINT NOT NULL, total TWODECINT NOT NULL, num_items_sold FOURDECINT NOT NULL, sale_date TEXT NOT NULL, sale_time TEXT NOT NULL, cash_used TWODECINT NOT NULL, cc_used TWODECINT NOT NULL, is_voided BOOLEAN NOT NULL)''')
cursor.execute('''CREATE TABLE sale_items(sale_id INTEGER NOT NULL, price_at_sale TWODECINT NOT NULL, quantity FOURDECINT NOT NULL, item_id INTEGER NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(sale_id) ON DELETE RESTRICT, FOREIGN KEY(item_id) REFERENCES inventory(item_id) ON DELETE RESTRICT)''')
cursor.execute('''CREATE TABLE categories(category_id INTEGER PRIMARY KEY NOT NULL, category_name TEXT NOT NULL, parent_id INTEGER REFERENCES categories(category_id))''')
cursor.execute('''CREATE TABLE vendors(vendor_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, vendor_name TEXT NOT NULL)''')

cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Camping", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Candy & Snacks", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Fishing", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Foodstuffs", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("General Merch", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Gifts", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Misc.", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("RV", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Souvenirs", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Summer Fun", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("TBC Merch", ))
cursor.execute('''INSERT INTO categories VALUES (NULL, ?, NULL)''', ("Toys & Hobby", ))

cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('BBQ Supplies', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Blankets, Bajas & Pillows', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camp Books', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camp Cookware', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camp Tools & Tent Stakes', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Campfire Cooking', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Campfire Items and Starters', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camping Accessories', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camping Bedding', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ceramics Mugs', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Cooking & Campfire Books', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Coolers and Thermals', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Decorative & Impulse Lights', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Flashlights (including head lamps)', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Fuels and Matches', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Furniture & Hammocks', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Hiking Gear', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Insect Control', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Knives', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Lanterns', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Nature Guides & Maps', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Notebooks & Journals', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Outdoor Adventure Books', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Packs', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Pet Supplies', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Picnic Products', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Propane Cooking and Lighting', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Raingear', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ropes, Cords, Tiedowns', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Shopping Bags & Totes', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Tarps, Tents, Shelters', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Waterproof Pouches and Bags', 1)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Candy and Jerky', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Hats & Bandanas', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Jewelry & Novelties', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Jokes and Tricks', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Keychains', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Light Up Fun', 2)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Fishing Accessories', 3)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Lures', 3)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Nets', 3)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Rod and Reel Combos', 3)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Tackle', 3)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Chips', 4)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Cookies', 4)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Dry Goods', 4)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ice Cream', 4)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Refrigerated', 4)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Brooms Cleaning Supplies', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Drinkware', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Hardware Related Products', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Health and Beauty Aids', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Household Electric', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Kitchen Utensils', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Kitchenware', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Laundry Products', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Other Household Items', 5)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Antler Look Theme', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Baskets', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Bear Theme', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Big Foot', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Birdhouses', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Cabin & Lodge Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camping and RV Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Canoe and Paddle Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Cute/Fantasy Theme', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Dream Catchers', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Fur Figures', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Lamps', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Magnets', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Moose Theme', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ornaments', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Other Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Pens', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Picture Frames', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Seaside Themes', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Signs and Plaques', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Smore Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Stuffed Animals', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Wildlife Theme', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Wind Chimes and Spinners', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Wood Gifts', 6)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Batteries', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Merchandising', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Other Items/Notions', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Phone Accessories & Bluetooth', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Playing Cards', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('PPE', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Winter Items', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Winter Wear', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Work Gloves', 7)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Automotive', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Drinking Water Hoses & Acc', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ground Coverings & Awning Mats', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Leveling Towing', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Patio Lights & Accessories', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('RV Accessories', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('RV Cleaning Products', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('RV Electrical', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('RV Parts & Maintenance', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Sewer Products', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Toilet Chemicals and Tissue', 8)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Beach Towels', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Flags, Pennants, Yard Spinners', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Footwear', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Inflatable Floats, Tubes, Rafts', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Outdoor Fun & Sport Items', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Ski Tubes, Towables, Life Preserv', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Sunglasses', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Suntan Lotion', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Swim Goggles and Fins', 10)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('N/A', 11)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Action Figures', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Activity Books', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Arts and Crafts', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Bubbles, Traditional Toys', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Camper Toys', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Cap Guns, Caps', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Fur Figures', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Games', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Gross & Squishy', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Guns, Action Toys', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Reptiles & Bugs', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Sand Toys', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('School Supplies', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Toys', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Vehicles, Die Cast', 12)''')
cursor.execute('''INSERT INTO categories (category_name, parent_id) VALUES ('Water Guns, Water Bombs', 12)''')

cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("ABC 123")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("ACME")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Aldi's")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Cheap Carls")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("D&D Distributing")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Dollar Tree")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Gib Carson")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Kohl's")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Puka Creations")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Restaurant Depot")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Sam's Club")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Shoprite")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Walmart")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Wilcor")''')
cursor.execute('''INSERT INTO vendors (vendor_name) VALUES ("Zoologee")''')

cursor.execute('''SELECT * FROM old_sales''')

results = cursor.fetchall()

for row in results:
    cursor.execute('''INSERT INTO sales VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''', (row[0], row[1], row[2], row[3], row[4], row[5] * Decimal('100'), row[6], row[7], row[8], row[9], row[10]))

cursor.execute('''SELECT sale_id, price, quantity, barcode FROM old_saleitems''')

saleitem_results = cursor.fetchall()

for row in saleitem_results:
    cursor.execute('''INSERT INTO sale_items(sale_id, price_at_sale, quantity, item_id) VALUES (?, ?, ?, (SELECT coalesce((select item_id from old_inventory where barcode = ? limit 1), -1) from old_saleitems))''', (row[0], row[1], row[2] * Decimal('100'), row[3]))


cursor.execute('''SELECT * FROM old_inventory''')

for row in cursor.fetchall():
    cursor.execute('''INSERT INTO inventory VALUES (?, ?, ?, ?, ?, ?, (SELECT category_id FROM categories WHERE category_name = ?), (SELECT category_id FROM categories WHERE category_name = ?), (SELECT vendor_id FROM vendors WHERE vendor_name = ?))''', (row[0], row[1], row[2], row[3], row[4], row[5] * Decimal('100'), row[6], row[7], row[8]))

conn.commit()